let students = `[
    {"name":"Бичинюк Максим (211Б)","points":[
        [1,"https://github.com/imaksb/lab1-web","https://imaksb.github.io/lab1-web/",""],
        [1,"https://github.com/imaksb/book-store-django","https://github.com/imaksb/book-store-django",""],
        [1,"https://github.com/imaksb/bookStoreV2","https://bookstore3424.netlify.app",""],
        [0,"","",""],
        [1,"","",""],
        0,""
    ]},
    {"name":"Мельник Володимир","points":[
        [1,"https://github.com/kap1yn/web_lab_1","https://kap1yn.github.io/web_lab_1/",""],
        [1,"https://github.com/kap1yn/lab_web_2","https://kap1yn.github.io/lab_web_2/",""],
        [1,"https://github.com/kap1yn/web_3","https://kap1yn.github.io/web_3/",""],
        [1,"https://github.com/bishkar/catalogue_api","https://kap1yn.github.io/web_3/",""],
        [1,"https://github.com/bishkar/fractals/","https://transcendent-toffee-5cee88.netlify.app/",""],
        0,""]},
    {"name":"Міхалчан Максиміліан","points":[
        [1,"https://github.com/MaximilianMMM/Laba__1__Web","https://maximilianmmm.github.io/Laba__1__Web/school.html",""],
        [1,"https://github.com/MaximilianMMM/WEB_Laba_2","https://maximilianmmm.github.io/WEB_Laba_2/",""],
        [1,"https://github.com/MaximilianMMM/WEB_Laba_3","https://maximilianmmm.github.io/WEB_Laba_3/",""],
        [1,"https://github.com/MaximilianMMM/Laba_4","https://maximilianmmm.github.io/Laba_4/",""],
        [0,"","",""],
        0,""]},
    {"name":"Назарко Артем","points":[
        [1,"https://github.com/WebTechCNU/l.a.b_1","https://webtechcnu.github.io/l.a.b_1/",""],
        [1,"https://github.com/WebTechCNU/Laba_2.git","https://webtechcnu.github.io/Laba_2/",""],
        [0.8,"https://github.com/18Artem26/Laba_3","https://18artem26.github.io/Laba_3/","Alerts; Too much GPT code"],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Отрубчак Тетяна","points":[
        [0.8,"https://github.com/taniaotr/laba1_web/tree/main","https://taniaotr.github.io/laba1_web/pages/index.html","GPT-generated; lab not presented offline"],
        [1,"https://taniaotr.github.io/web_lab23/","https://github.com/taniaotr/web_lab23",""],
        [1,"https://taniaotr.github.io/web_lab23/","https://github.com/taniaotr/web_lab23",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Ратушняк Наталія","points":[
        [1,"https://github.com/RNatali/Laboratory_1","https://rnatali.github.io/Laboratory_1/button.html#", ""],
        [1,"https://github.com/RNatali/Laboratory-2","https://rnatali.github.io/Laboratory-2/file.html",""],
        [1,"https://github.com/RNatali/Laboratory-3","https://rnatali.github.io/Laboratory-3/",""],
        [1,"https://github.com/RNatali/lab4","https://rnatali.github.io/lab4/",""],
        [0,"","",""],
        0,""
    ]},
    {"name":"Розновський Роман","points":[
        [0.8,"https://roznovskyi.github.io/weblab1/","https://roznovskyi.github.io/weblab1/","Late submit"],
        [1,"https://roznovskyi.github.io/weblab23/","https://roznovskyi.github.io/weblab23/",""],
        [1,"https://roznovskyi.github.io/weblab23/","https://roznovskyi.github.io/weblab23/",""],
        [0,"","",""],
        [0,"","",""],
        0,""
    ]},
    {"name":"Рябов Олександр","points":[
        [0.8,"https://github.com/Sashko192/Lab1_Riabov","https://sashko192.github.io/Lab1_Riabov/","GPT-generated; lab not presented offline"],
        [1,"https://github.com/Sashko192/Riabov_lab2","https://sashko192.github.io/Riabov_lab2/",""],
        [1,"https://github.com/Sashko192/Lab3__Riabov","https://sashko192.github.io/Lab3__Riabov/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Сметанюк Михайло","points":[
        [1,"https://github.com/MishaSmetaniuk/web_1","https://mishasmetaniuk.github.io/web_1/",""],
        [1,"https://github.com/MishaSmetaniuk/web_2_3","https://mishasmetaniuk.github.io/web_2_3/",""],
        [0.8,"https://github.com/MishaSmetaniuk/web_2_3","https://mishasmetaniuk.github.io/web_2_3/","lab not presented offline"],
        [1,"https://github.com/MishaSmetaniuk/web_4/","https://github.com/MishaSmetaniuk/web_4/",""],
        [0,"","",""],
        0,""]},
    {"name":"Тимчук Олександр","points":[
        [0.8,"https://github.com/TymchukAlex/Laba_1_WEB","https://tymchukalex.github.io/Laba_1_WEB/","No navigation; No hoverable info display;"],
        [0.8,"https://github.com/TymchukAlex/Laba_2_WEB","https://tymchukalex.github.io/Laba_2_WEB/","Some GPT code"],
        [0.5,"https://tymchukalex.github.io/Laba_3_WEB/","https://tymchukalex.github.io/Laba_3_WEB/","No presence on labs; no codebase link; no histograms"],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Токарчук Роман","points":[
        [1,"https://github.com/RoomToom/WEBLAB1.1","https://roomtoom.github.io/WEBLAB1.1/",""],
        [1,"https://github.com/RoomToom/weblab2","https://roomtoom.github.io/weblab2/",""],
        [0.8,"https://github.com/RoomToom/LAB3TURBO","https://roomtoom.github.io/LAB3TURBO/","No charts; Too much GPT js code"],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Черней Олексій","points":[
        [1,"https://github.com/Kibooto/Lab1","", ""],
        [1,"https://github.com/Kibooto/Lab2","https://kibooto.github.io/Lab2/", ""],
        [1,"https://github.com/Kibooto/Lab3","",""],
        [1,"https://github.com/Kibooto/Lab4","",""],
        [1,"","",""],
        0,""
    ]},
    {"name":"Чеховський Станіслав","points":[
        [1,"https://github.com/MORCHIK1/JS","https://morchik1.github.io/JS/index.html",""],
        [1,"https://github.com/MORCHIK1/JS2.git","https://morchik1.github.io/JS2/",""],
        [1,"https://github.com/MORCHIK1/JS2","https://morchik1.github.io/JS2/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Шмігельська Анна","points":[
        [1,"https://github.com/annieshm/first-lab_Shmihelska","https://annieshm.github.io/first-lab_Shmihelska/",""],
        [1,"https://github.com/taniaotr/web_lab23","https://annieshm.github.io/Lab2-3/index.html",""],
        [1,"https://github.com/taniaotr/web_lab23","https://annieshm.github.io/Lab2-3/index.html",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Агієв Микола (201А)","points":[
        [1,"https://github.com/Kolya3578/Lab1-JS","https://kolya3578.github.io/Lab1-JS/Lab%20%E2%84%961/index.html","Please, no GPT in the future"],
        [1,"https://github.com/Kolya3578/Lab2-JS","https://kolya3578.github.io/Lab2-JS/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Апопій Георгій ","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Білан Олександра ","points":[
        [1,"https://github.com/ccapJackSparroww/-1","https://ccapjacksparroww.github.io/-1/Multiplying.html","Please, no GPT in the future"],
        [1,"https://github.com/ccapJackSparroww/-2-","https://ccapjacksparroww.github.io/-2-/WEB%20%D0%BB%D0%B0%D0%B1%D0%B0%202/source/index.html",""],
        [0.8,"https://github.com/ccapJackSparroww/laba3-Bilan","","No deploy link; too much GPT code"],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Бричак Олег","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Бурдужук Інна","points":[
        [1,"https://github.com/1VANILKA/lab_1","https://1vanilka.github.io/lab_1/School.html", ""],
        [1,"https://github.com/1VANILKA/l_2","https://1vanilka.github.io/l_2/",""],
        [1,"https://github.com/1VANILKA/Web_lab3","https://1vanilka.github.io/Web_lab3/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Вадяк Валерій","points":[
        [0.8,"https://github.com/vachokvalerchik/vadiak_lab_1","https://vachokvalerchik.github.io/vadiak_lab_1/HTML/index.html","No presence on lab; (4) Hoverable logo; Bad naming practice (task1.js, task2.js etc.)"],
        [1,"https://github.com/vachokvalerchik/vachokvalerchik-vadiak_lab_2","https://vachokvalerchik.github.io/vachokvalerchik-vadiak_lab_2/LAB%202/HTML/index.html",""],
        [1,"https://vachokvalerchik.github.io/vadiak_lab_3/HTML/shop.html","https://vachokvalerchik.github.io/vadiak_lab_3/HTML/shop.html",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Галушка Віктор","points":[
        [1,"https://github.com/ViktorHalushka/WEB_lab_1","https://viktorhalushka.github.io/WEB_lab_1/text.html","part1.html, part2.html - good luck debugging that in the future =)"],
        [1,"https://github.com/ViktorHalushka/Lab_2","https://viktorhalushka.github.io/Lab_2/index.html",""],
        [1,"https://github.com/ViktorHalushka/Lab_3","https://viktorhalushka.github.io/Lab_3/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Грищенко Анастасія","points":[
        [0.8,"https://github.com/Anastas12345/lab1_HryshchenkoAnastasiia","https://maxvonlancaster.github.io/lab1_HryshchenkoAnastasiia/main.html","Gpt code, no separate js files"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Гуцуляк Максим","points":[
        [1,"https://github.com/Makshutsuliak/web_lab_1","https://makshutsuliak.github.io/web_lab_1/html/index.html",""],
        [1,"https://github.com/Makshutsuliak/web_lab_2","https://makshutsuliak.github.io/web_lab_2/lab%202/index.html",""],
        [1,"https://github.com/Makshutsuliak/web_lab_3","https://makshutsuliak.github.io/web_lab_3/lab%203/index.html",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Жалоба Павло","points":[
        [1,"https://github.com/ZhalobaPav/Lb1/tree/main/1","https://maxvonlancaster.github.io/Lb1/1/main",""],
        [1,"https://github.com/ZhalobaPav/3","https://zhalobapav.github.io/3/products.html",""],
        [1,"https://github.com/ZhalobaPav/3","https://zhalobapav.github.io/3/products.html",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Завалецький Владислав","points":[
        [1,"https://github.com/GarniyNegro/OIT_1","https://garniynegro.github.io/OIT_1/lab1/lab1.1/index.html","Please, no GPT in the future"],
        [1,"https://github.com/GarniyNegro/Web_2lab","https://garniynegro.github.io/Web_2lab/",""],
        [1,"https://github.com/GarniyNegro/lab3","https://garniynegro.github.io/lab3/","Please, no alerts in the future"],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Іванюк Богдан","points":[
        [0.5,"https://github.com/Bohdance/oit_labs","https://github.com/Bohdance/oit_labs","What is this? Please, read tasks to do. Please, deploy to github pages"],
        [0.8,"https://github.com/Bohdance/2lab","https://bohdance.github.io/2lab/info.html","No in-person presentation"],
        [0.8,"https://github.com/Bohdance/lab3_web","https://bohdance.github.io/lab3_web/info.html","No gistograms"],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Кирстюк Олександр","points":[
        [1,"https://github.com/ColdCapitan/Web-laroratory-1","https://coldcapitan.github.io/Web-laroratory-1/", ""],
        [1,"https://github.com/ColdCapitan/Web-Laboratory-2","https://coldcapitan.github.io/Web-Laboratory-2/",""],
        [1,"https://github.com/ColdCapitan/Web-laboratory-3","https://coldcapitan.github.io/Web-laboratory-3/",""],
        [1,"https://github.com/ColdCapitan/Web-Laboratory-4","https://coldcapitan.github.io/Web-Laboratory-4/",""],
        [0,"","",""],
        0,""]},
    {"name":"Козловський Василь","points":[
        [1,"https://github.com/VasylKozlovskyi2022/laba1","https://vasylkozlovskyi2022.github.io/laba1/index.html",""],
        [1,"https://github.com/VasylKozlovskyi2022/lab_2","https://vasylkozlovskyi2022.github.io/lab_2/",""],
        [1,"https://github.com/VasylKozlovskyi2022/lab_3","https://vasylkozlovskyi2022.github.io/lab_3/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Козуб Костянтин ","points":[
        [1,"https://github.com/37Lucky37/web_lab1_Kostya_Kozub","https://37lucky37.github.io/web_lab1_Kostya_Kozub/",""],
        [1,"https://github.com/37Lucky37/OIT_Lab2-3","https://37lucky37.github.io/OIT_Lab2-3/html/shop.html",""],
        [1,"https://github.com/37Lucky37/OIT_Lab2-3","https://37lucky37.github.io/OIT_Lab2-3/html/shop.html",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Козуб Назар ","points":[
        [1,"https://github.com/nazarkozub/web_lab1_Nazar_Kozub/tree/main/test","https://nazarkozub.github.io/web_lab1_Nazar_Kozub/test/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Корня Петро (Tickle Timpson)","points":[
        [1,"https://github.com/qhorsemorse/Js_lab1","https://qhorsemorse.github.io/Js_lab1/website3.0/side.html",""],
        [1,"https://github.com/qhorsemorse/Js_lab1/tree/main/lab_2","https://qhorsemorse.github.io/Js_lab1/lab_2/Products.html",""],
        [1,"https://github.com/qhorsemorse/Js_lab1/blob/main/lab_333/charts.js","https://qhorsemorse.github.io/Js_lab1/lab_333/cart.html",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Боднарюк Максим (208)","points":[
        [1,"https://github.com/Bodnamax/Bodnariuk.lab1","https://bodnamax.github.io/Bodnariuk.lab1/",""],
        [1,"https://github.com/Bodnamax/BodnariukLab2.git","https://bodnamax.github.io/BodnariukLab2/",""],
        [1,"https://bodnamax.github.io/Bodnariuk_Lab3/","https://bodnamax.github.io/Bodnariuk_Lab3/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Бурлака Ірина","points":[
        [1,"https://github.com/burlakaIryna/lab-1","https://burlakairyna.github.io/lab-1/",""],
        [1,"https://github.com/maxvonlancaster/Iryna","https://maxvonlancaster.github.io/Iryna/",""],
        [1,"https://github.com/burlakaIryna/lab3","https://maxvonlancaster.github.io/lab3-Iryna/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Вахнюк Вікторія","points":[
        [1,"https://github.com/viktoriavahniuk17/Laba1VV","https://viktoriavahniuk17.github.io/Laba1VV/",""],
        [1,"https://github.com/viktoriavahniuk17/flower","https://viktoriavahniuk17.github.io/flower/",""],
        [1,"https://github.com/viktoriavahniuk17/flower","https://viktoriavahniuk17.github.io/flower/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Віщак Андрій","points":[
        [1,"https://github.com/Andriu3245/lab1","https://andriu3245.github.io/lab1/",""],
        [1,"https://github.com/Andriu3245/lab2","https://andriu3245.github.io/lab2/",""],
        [1,"https://github.com/Andriu3245/lab3","https://andriu3245.github.io/lab3/",""],
        [1,"https://andriu3245.github.io/labs4/","https://andriu3245.github.io/labs4/",""],
        [0,"","",""],
        0,""]},
    {"name":"Власійчук Тетяна","points":[
        [1,"https://github.com/vlasiichuktetiana/lab.1","https://vlasiichuktetiana.github.io/lab.1/",""],
        [1,"https://github.com/vlasiichuktetiana/lab_2","https://vlasiichuktetiana.github.io/lab_2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Іванов Олексій","points":[
        [1,"","https://nimarchik.github.io/xwear/",""],
        [1,"","https://nimarchik.github.io/xwear/",""],
        [1,"","https://nimarchik.github.io/xwear/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Кострикова Анастасія","points":[
        [1,"https://github.com/NanaDrama/web-lab","https://nanadrama.github.io/web-lab/",""],
        [1,"","https://nanadrama.github.io/online-shop-simple/",""],
        [1,"","https://nanadrama.github.io/online-shop-simple/",""],
        [1,"","https://nanadrama.github.io/online-shop-simple/",""],
        [0,"","",""],
        0,""]},
    {"name":"Коханюк Станіслав","points":[
        [1,"https://github.com/staaskokhaniukk/lab_1","https://staaskokhaniukk.github.io/lab_1/",""],
        [1,"https://staaskokhaniuk.github.io/Lab2-3/","https://staaskokhaniuk.github.io/Lab2-3/",""],
        [1,"https://staaskokhaniuk.github.io/Lab2-3/","https://staaskokhaniuk.github.io/Lab2-3/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Сворожинськи Володимир","points":[
        [1,"https://github.com/volodiacv/laba-1-2","https://volodiacv.github.io/laba-1-2/",""],
        [1,"https://github.com/volodiacv/laba-1-2","https://volodiacv.github.io/laba-1-2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Скіцько Віолєтта","points":[
        [1,"https://github.com/vviolettaaa/Laba1","https://vviolettaaa.github.io/Laba1/",""],
        [1,"https://github.com/vviolettaaa/Fashion","https://vviolettaaa.github.io/Fashion/index.html",""],
        [1,"https://github.com/vviolettaaa/Fashion","https://vviolettaaa.github.io/Fashion/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Стужук Владислав","points":[
        [0.5,"","https://stuzhukv.github.io/llab1/","Stolen from Скіцько Віолєтта"],
        [1,"","https://stuzhukv.github.io/laab2/",""],
        [0.5,"","https://stuzhukv.github.io/laab2/","No cart; no modals; no histogram"],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Тарадай Крістіна","points":[
        [1,"https://github.com/Kris070704/lab_1_Taradai","https://kris070704.github.io/lab_1_Taradai/lab1-Taradai/index",""],
        [1,"https://github.com/Kris070704/lab_2_taradai","https://kris070704.github.io/lab_2_taradai/",""],
        [1,"https://github.com/Kris070704/lab3","https://kris070704.github.io/lab3/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Татарин Діана","points":[
        [1,"https://github.com/Dianatataryn/lab.1","https://dianatataryn.github.io/lab.1/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Тимчишин Анастасія","points":[
        [1,"https://github.com/Nastya3333333333333/laba1-sem2-","https://nastya3333333333333.github.io/laba1-sem2-/index.html","Great!"],
        [1,"https://github.com/Nastya3333333333333/Vinyl2-3","https://nastya3333333333333.github.io/Vinyl2-3/index%20.html",""],
        [1,"https://github.com/Nastya3333333333333/Vinyl2-3","https://nastya3333333333333.github.io/Vinyl2-3/index%20.html",""],
        [1,"https://github.com/Nastya3333333333333/Vinyl2-3","https://nastya3333333333333.github.io/Vinyl2-3/index%20.html",""],
        [0,"","",""],
        0,""]},
    {"name":"Хімчинський Володимир","points":[
        [1,"https://github.com/Blazewozy/laba1_2","https://thunderous-toffee-df4d23.netlify.app/#contact",""],
        [1,"https://github.com/Blazewozy/laba1_2","https://thunderous-toffee-df4d23.netlify.app/#contact",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Чепига Богдана","points":[
        [1,"https://github.com/Dana2704/-1","https://dana2704.github.io/-1/",""],
        [1,"https://github.com/Dana2704/lb2","https://dana2704.github.io/lb2/",""],
        [1,"https://github.com/Dana2704/3lb","https://dana2704.github.io/3lb/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Денис Докторович (211А)","points":[
        [1,"https://github.com/Normn24/Lab1.git","https://normn24.github.io/Lab1/",""],
        [1,"https://github.com/Normn24/lab2.3","https://fascinating-alpaca-13a73e.netlify.app/",""],
        [1,"https://github.com/Normn24/lab2.3","https://fascinating-alpaca-13a73e.netlify.app/",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
        {"name":"Басараба Віталій","points":[
            [1,"https://github.com/maxvonlancaster/Lab-1-","https://maxvonlancaster.github.io/Lab-1-/",""],
            [1,"https://github.com/Valience/labaratorna2","https://valience.github.io/labaratorna2/#",""],
            [1,"https://valience.github.io/labaratorna3","https://github.com/Valience/labaratorna3",""],
            [0,"","",""],
            [0,"","",""],
            0,""]},
        {"name":"Гаць Іван","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Герасименко Роман(індивідуальник)","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Гладчук Денис","points":[
            [1,"https://github.com/whyareyousilent/weblab1","https://whyareyousilent.github.io/weblab1/",""],
            [1,"https://github.com/whyareyousilent/weblab2","https://whyareyousilent.github.io/weblab2/",""],
            [0,"","",""],
            [0,"","",""],
            [0,"","",""],
            0,""]},
        {"name":"Гордійчук Василь","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Груба Софія(індивідуальник)","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Данко Володимир","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Ільницький Дмитро","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Каліструк Максим","points":[
            [1,"https://github.com/MGCc0/WebLab1","https://mgcc0.github.io/WebLab1/Lab1Maks/",""],
            [0,"","",""],
            [0,"","",""],
            [0,"","",""],
            [0,"","",""],
            0,""]},
        {"name":"Лучик Євген","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Любківський Максим","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Макар Марія (індивідуальник)","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]}
]`;