let students = `[
    {"name":"Андрицький Михайло Олексійович","points":[
[1,"https://github.com/MykhailoAn/portfolio", "77 C"],
[1,"https://github.com/MykhailoAn/project0"],
[0,""],
[0,""],
[0,""]]},
    {"name":"Балан Олександр Ігорович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":"Гловацький Олексій Олександрович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":"Дирда Ілля Петрович","points":[
[1,"https://github.com/dyrda1/portfolio", "82 B"],
[1,"https://github.com/dyrda1/lab2"],
[1,"https://github.com/dyrda1/individual"],
[0,""],
[1,"https://github.com/dyrda1/individual"]]},
    {"name":"Каркавчук Дмитро Вікторович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
{"name":"Ковбінька Олексій Сергійович","points":[
    [0,""],
    [0,""],
    [0,""],
    [0,""],
    [0,""]]},
{"name":"Лук'ян Олександр Нуміторович","points":[
    [1,"", "78 C"],
    [1,""],
    [1,""],
    [0,""],
    [0,""]]},
{"name":"Лучик Павло Вікторович","points":[
    [0,"", "51 E"],
    [0,""],
    [0,""],
    [0,""],
    [0,""]]},
{"name":"Николюк Андрій Дмитрович","points":[
    [0,""],
    [0,""],
    [0,""],
    [0,""],
    [0,""]]},
    {"name":"Саука Михайло Валерійович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":"Сироїд Вадим Костянтинович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":"Стрілак Олександр Віталійович","points":[
[0,"", "53 E"],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":"Тодосійчук Михайло Іванович","points":[
[0,"", "52 E"],
[0,""],
[0,""],
[0,""],
[0,""]]},
{"name":"Токар Іван Дмитрович","points":[
    [1,"", "76 C"],
    [0,""],
    [1,""],
    [1,""],
    [0,""]]},
{"name":"◦ Анатійчук Роман Васильович","points":[
    [1,"https://github.com/WebTechCNU/anatiichuk_lab1", "85 B"],
    [1,"https://github.com/WebTechCNU/anatiichuk_lab2"],
    [1,"https://github.com/WebTechCNU/anatiichuk_labb3"],
    [0,""],
    [0,""]]},
{"name":" ◦ Антонюк Костянтин Олегович","points":[
    [0,""],
    [0,""],
    [0,""],
    [0,""],
    [0,""]]},
{"name":" ◦ Білинський Ян Йосипович","points":[
    [0,"85 B"],
    [1,"https://github.com/WebTechCNU/Bilynskyi_lab2"],
    [1,"https://github.com/WebTechCNU/Bilynskyi_lab3"],
    [1,"https://github.com/WebTechCNU/Bilynskyi_lab4"],
    [0,""]]},
    {"name":" ✓ Бледюк Антон Петрович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":" ◦ Вікован Валентин Костянтинович","points":[
[1,"https://github.com/WebTechCNU/JS-Frameworks_Vikovan_307_Lab1", "95 A"],
[1,"https://github.com/WebTechCNU/Lab--2-Vikovan"],
[0,""],
[1,"https://github.com/cryme666/simple-todo-app"],
[1,"https://github.com/cryme666/simple-todo-app"]]},
    {"name":" ✓ Галюк Олег Олександрович","points":[
[1,"https://github.com/str-djkr/LAb_js", "82 B"],
[1,"https://github.com/str-djkr/LAb_js"],
[0,""],
[1,"https://github.com/str-djkr/LAb_js"],
[0,""]]},
    {"name":" ◦ Гаюк Євген Миколайович","points":[
[1,"https://github.com/WebTechCNU/lab1-Yevhen-Haiuk", "92 A"],
[1,"https://github.com/WebTechCNU/lab2-Yevhen-Haiuk"],
[1,"https://github.com/WebTechCNU/lab3-Yevhen-Haiuk"],
[1,"https://github.com/WebTechCNU/lab4-Yevhen-Haiuk"],
[0,""]]},
{"name":" ◦ Граб Андрій Миколайович","points":[
    [0,"", "75 С"],
    [1,"https://github.com/WebTechCNU/Hrab_Lab2-1-"],
    [1,"https://github.com/WebTechCNU/Hrab_Lab3-1-"],
    [1,"https://github.com/WebTechCNU/Hrab_Lab4"],
    [0,""]]},
{"name":" ◦ Дейнеко Олександр Павлович","points":[
    [0,""],
    [0,""],
    [0,""],
    [0,""],
    [0,""]]},
{"name":" ◦ Деревчук Артем Вячеславович","points":[
    [0,""],
    [0,""],
    [0,""],
    [0,""],
    [0,""]]},
    {"name":" ◦ Житарюк Едуард Сергійович","points":[
[1,"", "95 A"],
[1,""],
[1,""],
[1,""],
[1,""]]},
    {"name":" ◦ Завялець Олександра Павлівна","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":"Мігальчан Теодор","points":[
[1,"https://github.com/WebTechCNU/laba1_mikhalchan", "50 E"],
[0,""],
[0,""],
[0,""],
[0,""]]},
{"name":"Іванова Катерина Вячеславівна","points":[
    [1,"https://github.com/WebTechCNU/lab1_Ivanova_webtech", "90 A"],
    [1,"https://github.com/WebTechCNU/Ivanova_lab2_js"],
    [1,"https://github.com/WebTechCNU/lab3_Ivanova_307_"],
    [1,"https://github.com/WebTechCNU/lab4_Ivanova_307_"],
    [0,""]]},
{"name":"Кирлан Іван Джованні","points":[
    [1,"https://github.com/WebTechCNU/JS-Frameworks_Kyrlan_307_Lab1", "95 A"],
    [1,"https://github.com/WebTechCNU/JS-Frameworks_Kyrlan_307_Lab2"],
    [1,"https://github.com/WebTechCNU/JS-Frameworks_Kyrlan_307_Lab3"],
    [1,"https://github.com/WebTechCNU/JS-Frameworks_Kyrlan_307_Lab4"],
    [0,""]]},
{"name":"Кіященко Михайло Леонідович","points":[
    [1,"https://github.com/WebTechCNU/kiiashchenko_lab1", "86 B"],
    [1,"https://github.com/WebTechCNU/kiiashchenko_lab2_js"],
    [1,"https://github.com/WebTechCNU/kiiashchenko_lab3_js"],
    [0,""],
    [0,""]]},
    {"name":"Маланчук Сергій Михайлович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
    {"name":"Мироник Анастасія Сергіївна","points":[
[1,"", "90 A"],
[1,""],
[1,""],
[1,""],
[0,""]]},
    {"name":"Мігальчан Теодор Іванович","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
{"name":"Петрук Юрій Ярославович   П","points":[
    [1,"https://github.com/WebTechCNU/petruk-lab-1", "75 C"],
    [1,"https://github.com/WebTechCNU/project0"],
    [0,""],
    [0,""],
    [0,""]]},
{"name":"Попович Ігор Павлович","points":[
    [1,"https://github.com/WebTechCNU/Lab1PopovichIgor", "82 B"],
    [1,"https://github.com/WebTechCNU/Lab2PopovichIgor"],
    [1,"https://github.com/WebTechCNU/Lab3PopovichIgor"],
    [0,""],
    [0,""]]},
{"name":"Саєнко Святослав Олексійович","points":[
    [0,""],
    [0,""],
    [0,""],
    [0,""],
    [0,""]]},
    {"name":"Фрідман Юрій Юрійович","points":[
[1,"https://github.com/WebTechCNU/lab1_Fridman", "95 A"],
[1,"https://github.com/WebTechCNU/lab2_Fridman"],
[1,"https://github.com/WebTechCNU/lab3_Fridman"],
[1,"https://github.com/WebTechCNU/lab4_Fridman"],
[0,""]]},
    {"name":"Чубрей Андрій Володимирович    П","points":[
[1,"https://github.com/WebTechCNU/lb1-Andrii-Chubrei-307", "95 A"],
[1,"https://github.com/WebTechCNU/lb2-Project0-Andrii-Chubrei-307"],
[1,"https://github.com/WebTechCNU/lb3-Angular-Andrii-Chubrei-307"],
[1,"https://github.com/WebTechCNU/lb4-React-Andrii-Chubrei-307"],
[0,""]]},
    {"name":"Шинкура Марія Владиславівна","points":[
[0,""],
[0,""],
[0,""],
[0,""],
[0,""]]},
{"name":"Яцюк Марія","points":[
    [1,"https://github.com/MariykaYatsiuk/web", "90 A"],
    [1,"https://github.com/WebTechCNU/lab2_Yatsiuk_js_frameworks"],
    [1,"https://github.com/MariykaYatsiuk/web3"],
    [1,"https://github.com/MariykaYatsiuk/web4yatsiuk"],
    [0,""]]},
    {"name":"Журат Настя","points":[
        [0,""],
        [0,""],
        [0,""],
        [0,""],
        [1,""]]}
]`;