let students = `[
    {"name":"Бичинюк Максим (211Б)","points":[
        [1,"https://github.com/imaksb/lab1-web","https://imaksb.github.io/lab1-web/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""
    ]},
    {"name":"Мельник Володимир","points":[
        [1,"https://github.com/kap1yn/web_lab_1","https://kap1yn.github.io/web_lab_1/",""],
        [1,"https://github.com/kap1yn/lab_web_2","https://kap1yn.github.io/lab_web_2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Міхалчан Максиміліан","points":[
        [1,"https://github.com/MaximilianMMM/Laba__1__Web","https://maximilianmmm.github.io/Laba__1__Web/school.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Назарко Артем","points":[
        [1,"https://github.com/WebTechCNU/l.a.b_1","https://webtechcnu.github.io/l.a.b_1/",""],
        [1,"https://github.com/WebTechCNU/Laba_2.git","https://webtechcnu.github.io/Laba_2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Отрубчак Тетяна","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Ратушняк Наталія","points":[
        [1,"https://github.com/RNatali/Laboratory_1","https://rnatali.github.io/Laboratory_1/button.html#", ""],
        [1,"https://github.com/RNatali/Laboratory-2","https://rnatali.github.io/Laboratory-2/file.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""
    ]},
    {"name":"Розновський Роман","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""
    ]},
    {"name":"Рябов Олександр","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Сметанюк Михайло","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Тимчук Олександр","points":[
        [0.5,"https://github.com/TymchukAlex/Laba_1_WEB","https://tymchukalex.github.io/Laba_1_WEB/","No presence on lab; No navigation; No hoverable info display;"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Токарчук Роман","points":[
        [1,"https://github.com/RoomToom/WEBLAB1.1","https://roomtoom.github.io/WEBLAB1.1/",""],
        [1,"https://github.com/RoomToom/weblab2","https://roomtoom.github.io/weblab2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Черней Олексій","points":[
        [1,"https://github.com/Kibooto/Lab1","", ""],
        [1,"https://github.com/Kibooto/Lab2","https://kibooto.github.io/Lab2/", ""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""
    ]},
    {"name":"Чеховський Станіслав","points":[
        [0,"https://github.com/MORCHIK1/JS","https://morchik1.github.io/JS/index.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Шмігельська Анна","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Агієв Микола (201А)","points":[
        [1,"https://github.com/Kolya3578/Lab1-JS","https://kolya3578.github.io/Lab1-JS/Lab%20%E2%84%961/index.html","Please, no GPT in the future"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Апопій Георгій ","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Білан Олександра ","points":[
        [1,"https://github.com/ccapJackSparroww/-1","https://ccapjacksparroww.github.io/-1/Multiplying.html","Please, no GPT in the future"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Бричак Олег","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Бурдужук Інна","points":[
        [1,"https://github.com/1VANILKA/lab_1","https://1vanilka.github.io/lab_1/School.html", ""],
        [1,"https://github.com/1VANILKA/l_2","https://1vanilka.github.io/l_2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Вадяк Валерій","points":[
        [0.8,"https://github.com/vachokvalerchik/vadiak_lab_1","https://vachokvalerchik.github.io/vadiak_lab_1/HTML/index.html","No presence on lab; (4) Hoverable logo; Bad naming practice (task1.js, task2.js etc.)"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Галушка Віктор","points":[
        [1,"https://github.com/ViktorHalushka/WEB_lab_1","https://viktorhalushka.github.io/WEB_lab_1/text.html","part1.html, part2.html - good luck debugging that in the future =)"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Грищенко Анастасія","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Гуцуляк Максим","points":[
        [1,"https://github.com/Makshutsuliak/web_lab_1","https://makshutsuliak.github.io/web_lab_1/html/index.html",""],
        [1,"https://github.com/Makshutsuliak/web_lab_2","https://makshutsuliak.github.io/web_lab_2/lab%202/index.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Жалоба Павло","points":[
        [1,"https://github.com/ZhalobaPav/Lb1/tree/main/1","https://maxvonlancaster.github.io/Lb1/1/main",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Завалецький Владислав","points":[
        [1,"https://github.com/GarniyNegro/OIT_1","https://garniynegro.github.io/OIT_1/lab1/lab1.1/index.html","Please, no GPT in the future"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Іванюк Богдан","points":[
        [0.5,"https://github.com/Bohdance/oit_labs","https://github.com/Bohdance/oit_labs","What is this? Please, read tasks to do. Please, deploy to github pages"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Кирстюк Олександр","points":[
        [1,"https://github.com/ColdCapitan/Web-laroratory-1","https://coldcapitan.github.io/Web-laroratory-1/", ""],
        [1,"https://github.com/ColdCapitan/Web-Laboratory-2","https://coldcapitan.github.io/Web-Laboratory-2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Козловський Василь","points":[
        [1,"https://github.com/VasylKozlovskyi2022/laba1","https://vasylkozlovskyi2022.github.io/laba1/index.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Козуб Костянтин ","points":[
        [1,"https://github.com/37Lucky37/web_lab1_Kostya_Kozub","https://37lucky37.github.io/web_lab1_Kostya_Kozub/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Козуб Назар ","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Корня Петро (Tickle Timpson)","points":[
        [1,"https://github.com/qhorsemorse/Js_lab1","https://qhorsemorse.github.io/Js_lab1/website3.0/side.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Боднарюк Максим (208)","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Бурлака Ірина","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Вахнюк Вікторія","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Віщак Андрій","points":[
        [1,"https://github.com/Andriu3245/lab1","https://andriu3245.github.io/lab1/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Власійчук Тетяна","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Іванов Олексій","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Кострикова Анастасія","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Коханюк Станіслав","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Сворожинськи Володимир","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Скіцько Віолєтта","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Стужук Владислав","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Тарадай Крістіна","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Татарин Діана","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Тимчишин Анастасія","points":[
        [1,"https://github.com/Nastya3333333333333/laba1-sem2-","https://nastya3333333333333.github.io/laba1-sem2-/index.html","Great!"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Хімчинський Володимир","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
    {"name":"Чепига Богдана","points":[
        [1,"https://github.com/Dana2704/-1","https://dana2704.github.io/-1/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
    {"name":"Денис Докторович (211А)","points":[
        [1,"https://github.com/Normn24/Lab1.git","https://normn24.github.io/Lab1/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        0,""]},
        {"name":"Басараба Віталій","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Гаць Іван","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Герасименко Роман(індивідуальник)","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Гладчук Денис","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Гордійчук Василь","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Груба Софія(індивідуальник)","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Данко Володимир","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Ільницький Дмитро","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Каліструк Максим","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Лучик Євген","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Любківський Максим","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]},
        {"name":"Макар Марія (індивідуальник)","points":[[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],[0,"","",""],0,""]}
]`;