let students = `[
    {"name":"Антонюк Анна (307)","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Боровскіх Євгеній","points":[
        [1,"https://github.com/Texofff/lab1","https://texofff.github.io/lab1/",""],
        [1,"https://github.com/Texofff/lab0","https://texofff.github.io/lab0/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Бринзан Анастасія","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Данко Геннадій","points":[
        [1,"https://gen0nim.github.io/Boostrap_lab/","https://gen0nim.github.io/Boostrap_lab/","Code link"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Квасницька Єлизавета","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Мельник Ольга","points":[
        [1,"https://github.com/Olia1802/Bootstrap","https://olia1802.github.io/Bootstrap/","Great Job!"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Мішин Олег","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Раренко Анастасія","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Агієв Микола (301)","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Апопій Георгій","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Білан Олександра","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Бричак Олег","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Бурдужук Інна","points":[
        [1,"https://github.com/SweetPomegranate/bootstrap1","https://sweetpomegranate.github.io/bootstrap1/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Вадяк Валерій","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Галушка Віктор","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Грищенко Анастасія","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Гуцуляк Максим","points":[
        [1,"https://github.com/Makshutsuliak/web_bootstrap4","https://makshutsuliak.github.io/web_bootstrap/bootstrap/index.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Жалоба Павло","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Завалецький Владислав","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Іванюк Богдан","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Кирстюк Олександр","points":[
        [1,"https://github.com/ColdCapitan/bootstrap","https://coldcapitan.github.io/bootstrap/",""],
        [1,"https://github.com/ColdCapitan/jQuery","https://coldcapitan.github.io/jQuery/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Козловський Василь","points":[
        [1,"https://github.com/WhoIsTheBot/BootStrapOne","https://whoisthebot.github.io/BootStrapOne/",""],
        [1,"https://github.com/WhoIsTheBot/To-Do-List-JQuery","https://whoisthebot.github.io/To-Do-List-JQuery/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Козуб Костянтин","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Козуб Назар","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Корня Петро","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Мацалковський Владислав","points":[
        [1,"https://github.com/DeFrag73/Project","https://defrag73.github.io/Project/","Great job!"],
        [1,"https://github.com/DeFrag73/to-do-app","https://defrag73.github.io/to-do-app/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Трипадуш Богдан","points":[
        [1,"https://argasdtiger.github.io/Bookish-Vanilla-JS-/src/index.html","https://github.com/ArgasDTiger/Researching-Wines--Vinho-Verde-","Great Job!"],
        [1,"https://github.com/ArgasDTiger/Frameworks-Lab-2","https://argasdtiger.github.io/Frameworks-Lab-2/",""],
        [0.8,"https://github.com/ArgasDTiger/Bookish/tree/main/client","https://github.com/ArgasDTiger/Bookish/tree/main/client","Note (maybe to myself): I'd like to see it"],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Малованюк Станіслав","points":[
        [1,"https://github.com/LUMA002/LUMA_shop_LAB4","https://luma002.github.io/LUMA_shop_LAB4/","Great Job!"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Лучик Іван","points":[
        [1,"https://github.com/LychokZZ/boostlab1","https://lychokzz.github.io/boostlab1/","Great Job!"],
        [1,"https://github.com/LychokZZ/lab2","https://lychokzz.github.io/lab2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Стрієнко Емма","points":[
        [1,"https://github.com/emmastrienko/solar-system-cards-tailwindcss","https://spiritual-good-bye-haha.surge.sh/","Great Job!"],
        [1,"https://github.com/emmastrienko/todo-list-jquery","https://emmastrienko.github.io/todo-list-jquery/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Лисенко Ніколя","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Мірчук Андрій","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Ратушняк Іван","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Романко Андрій","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Шахов Микита","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":" ","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]}
]`;