let students = `[
    {"name":"Антонюк Анна (307)","points":[
        [1,"https://github.com/AnnaAntonuk/boostrap1-","https://annaantonuk.github.io/boostrap1-/",""],
        [1,"https://github.com/AnnaAntonuk/project0","https://annaantonuk.github.io/project0/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Боровскіх Євгеній","points":[
        [1,"https://github.com/Texofff/lab1","https://texofff.github.io/lab1/",""],
        [1,"https://github.com/Texofff/lab0","https://texofff.github.io/lab0/",""],
        [0,"","",""],
        [1,"https://github.com/Texofff/lab2-angular","https://github.com/Texofff/lab2-angular",""],
        [0,"","",""]]},
    {"name":"Бринзан Анастасія","points":[
        [1,"https://github.com/Anastasis08/JavaScript1","https://anastasis08.github.io/JavaScript1/",""],
        [1,"https://github.com/Anastasis08/ToDoList","https://anastasis08.github.io/ToDoList/",""],
        [1,"https://github.com/Anastasis08/lab3Angular","https://anastasis08.github.io/lab3Angular/",""],
        [1,"https://github.com/Anastasis08/lab4React","https://github.com/Anastasis08/lab4React",""],
        [0,"","",""]]},
    {"name":"Данко Геннадій","points":[
        [1,"https://gen0nim.github.io/Boostrap_lab/","https://gen0nim.github.io/Boostrap_lab/","Code link"],
        [1,"https://github.com/Gen0nim/jQuery-toDo","https://gen0nim.github.io/jQuery-toDo/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Квасницька Єлизавета","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Мельник Ольга","points":[
        [1,"https://github.com/Olia1802/Bootstrap","https://olia1802.github.io/Bootstrap/","Great Job!"],
        [1,"https://github.com/Olia1802/Project0","https://olia1802.github.io/Project0/",""],
        [1,"https://github.com/Olia1802/Angular","https://github.com/Olia1802/Angular",""],
        [1,"https://github.com/Olia1802/React","https://github.com/Olia1802/React",""],
        [0,"","",""]]},
    {"name":"Мішин Олег","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Раренко Анастасія","points":[
        [1,"https://github.com/wanesssssty/lab1_bootsrap","https://wanesssssty.github.io/lab1_bootsrap/","Great!"],
        [1,"https://github.com/wanesssssty/project0","https://wanesssssty.github.io/project0/",""],
        [1,"https://github.com/wanesssssty/lab4_react","https://github.com/wanesssssty/lab4_react",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Агієв Микола (301)","points":[
        [1,"https://github.com/Kolya3578/JS-frame-lab1","https://kolya3578.github.io/JS-frame-lab1/index.html",""],
        [1,"https://github.com/Kolya3578/JS-frame-lab2","https://kolya3578.github.io/JS-frame-lab2/index.html",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Апопій Георгій","points":[
        [1,"https://github.com/goshkaaaa/lab1","https://goshkaaaa.github.io/lab1/",""],
        [0.5,"https://github.com/goshkaaaa/lab2","https://goshkaaaa.github.io/lab2/","No offline presentation, no styles, no input functionality"],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Білан Олександра","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Бричак Олег","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Бурдужук Інна","points":[
        [1,"https://github.com/SweetPomegranate/bootstrap1","https://sweetpomegranate.github.io/bootstrap1/",""],
        [1,"https://sweetpomegranate.github.io/react/dist/index.html","https://sweetpomegranate.github.io/react/dist/index.html",""],
        [0,"","",""],
        [1,"https://github.com/SweetPomegranate/react","https://sweetpomegranate.github.io/react/dist/index.html",""],
        [0,"","",""]]},
    {"name":"Вадяк Валерій","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Галушка Віктор","points":[
        [1,"https://github.com/ViktorHalushka/Lab_1","https://viktorhalushka.github.io/Lab_1/",""],
        [1,"https://viktorhalushka.github.io/Lab_2/","https://github.com/ViktorHalushka/Lab_2",""],
        [1,"https://github.com/ViktorHalushka/Lab_3_angular","",""],
        [1,"https://github.com/ViktorHalushka/Lab_4_react","",""],
        [0,"","",""]]},
    {"name":"Грищенко Анастасія","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Гуцуляк Максим","points":[
        [1,"https://github.com/Makshutsuliak/web_bootstrap4","https://makshutsuliak.github.io/web_bootstrap/bootstrap/index.html",""],
        [1,"https://makshutsuliak.github.io/todo_list/project0/index.html","https://makshutsuliak.github.io/todo_list/project0/index.html",""],
        [0,"","",""],
        [1,"https://github.com/Makshutsuliak/lab_react","",""],
        [0,"","",""]]},
    {"name":"Жалоба Павло","points":[
        [1,"https://github.com/ToTheTermsOfService/lab1","https://github.com/ToTheTermsOfService/lab1",""],
        [1,"https://github.com/ToTheTermsOfService/lb2","https://github.com/ToTheTermsOfService/lb2",""],
        [0,"","",""],
        [1,"https://github.com/ToTheTermsOfService/lb4","",""],
        [0,"","",""]]},
    {"name":"Завалецький Владислав","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Іванюк Богдан","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Кирстюк Олександр","points":[
        [1,"https://github.com/ColdCapitan/bootstrap","https://coldcapitan.github.io/bootstrap/",""],
        [1,"https://github.com/ColdCapitan/jQuery","https://coldcapitan.github.io/jQuery/",""],
        [1,"https://github.com/ColdCapitan/React","https://superb-churros-730143.netlify.app/#info",""],
        [0,"","",""],
        [1,"https://github.com/ColdCapitan/MERN","https://chipper-kleicha-30c78a.netlify.app",""]]},
    {"name":"Козловський Василь","points":[
        [1,"https://github.com/WhoIsTheBot/BootStrapOne","https://whoisthebot.github.io/BootStrapOne/",""],
        [1,"https://github.com/WhoIsTheBot/To-Do-List-JQuery","https://whoisthebot.github.io/To-Do-List-JQuery/",""],
        [1,"https://github.com/WhoIsTheBot/University-AngularTS","https://github.com/WhoIsTheBot/University-AngularTS",""],
        [1,"https://github.com/WhoIsTheBot/University-ReactTS","https://soft-dango-20afec.netlify.app/",""],
        [1,"https://github.com/WhoIsTheBot/mern_university","https://github.com/WhoIsTheBot/mern_university",""]]},
    {"name":"Козуб Костянтин","points":[
        [1,"https://github.com/37Lucky37/Lab1_Bootstrap.git","https://37lucky37.github.io/Lab1_Bootstrap/",""],
        [1,"https://github.com/37Lucky37/Lab2_ToDo_jQuery","https://37lucky37.github.io/Lab2_ToDo_jQuery",""],
        [1,"https://github.com/37Lucky37/Lab3_Angular","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Козуб Назар","points":[
        [1,"https://github.com/nazarkozub/JS_lab_1","https://nazarkozub.github.io/JS_lab_1/",""],
        [1,"https://github.com/nazarkozub/JS_lab_2","https://github.com/nazarkozub/JS_lab_2","Would be nice to have deploy ..."],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Корня Петро","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Мацалковський Владислав","points":[
        [1,"https://github.com/DeFrag73/Project","https://defrag73.github.io/Project/","Great job!"],
        [1,"https://github.com/DeFrag73/to-do-app","https://defrag73.github.io/to-do-app/",""],
        [0,"","",""],
        [1,"https://github.com/DeFrag73/lab-4-react","",""],
        [0,"","",""]]},
    {"name":"Трипадуш Богдан","points":[
        [1,"https://argasdtiger.github.io/Bookish-Vanilla-JS-/src/index.html","https://github.com/ArgasDTiger/Researching-Wines--Vinho-Verde-","Great Job!"],
        [1,"https://github.com/ArgasDTiger/Frameworks-Lab-2","https://argasdtiger.github.io/Frameworks-Lab-2/",""],
        [0.8,"https://github.com/ArgasDTiger/Bookish/tree/main/client","https://github.com/ArgasDTiger/Bookish/tree/main/client","Note (maybe to myself): I'd like to see it"],
        [1,"https://github.com/ArgasDTiger/Frameworks-Lab-4","https://github.com/ArgasDTiger/Frameworks-Lab-4",""],
        [1,"https://github.com/ArgasDTiger/Frameworks-Lab-5","https://frameworks-lab-5.onrender.com","Thanks for deploy, extra credit"]]},
    {"name":"Малованюк Станіслав","points":[
        [1,"https://github.com/LUMA002/LUMA_shop_LAB4","https://luma002.github.io/LUMA_shop_LAB4/","Great Job!"],
        [1,"https://github.com/LUMA002/js_fram_lab2","https://luma002.github.io/js_fram_lab2/",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Лучик Іван","points":[
        [1,"https://github.com/LychokZZ/boostlab1","https://lychokzz.github.io/boostlab1/","Great Job!"],
        [1,"https://github.com/LychokZZ/lab2","https://lychokzz.github.io/lab2/",""],
        [1,"https://github.com/LychokZZ/labb3","https://github.com/LychokZZ/labb3",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Стрієнко Емма","points":[
        [1,"https://github.com/emmastrienko/solar-system-cards-tailwindcss","https://spiritual-good-bye-haha.surge.sh/","Great Job!"],
        [1,"https://github.com/emmastrienko/todo-list-jquery","https://emmastrienko.github.io/todo-list-jquery/",""],
        [1,"https://github.com/emmastrienko/first-angular-project","https://github.com/emmastrienko/first-angular-project",""],
        [1,"https://github.com/emmastrienko/simple-todo-app-react","https://github.com/emmastrienko/simple-todo-app-react",""],
        [1,"https://github.com/emmastrienko/note-taking-app-mern","",""]]},
    {"name":"Лисенко Ніколя","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Мірчук Андрій","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Ратушняк Іван","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Романко Андрій","points":[
        [1,"https://github.com/Starks12/lab1_bootstrap","https://starks12.github.io/lab1_bootstrap/",""],
        [1,"https://github.com/Starks12/lab2_jquery","https://starks12.github.io/lab2_jquery/",""],
        [0.8,"https://github.com/Starks12/lab3_angular","https://starks12.github.io/lab3_angular","No offline presentation"],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Шахов Микита","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]},
    {"name":"Марчук","points":[
        [0.8,"https://github.com/Andiry-sys/to-do-list","","No offline presentation, no deploy link"],
        [0,"","",""],
        [0.8,"https://github.com/Andiry-sys/to-do-list","","No offline presentation, no deploy link"],
        [0,"","",""],
        [0,"","",""]]},
    {"name":" ","points":[
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""],
        [0,"","",""]]}
]`;